name: flutter_gertec
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  auto_size_text: ^3.0.0
  flutter_masked_text2: ^0.9.1
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/xmlSat/arq_cancelamento.xml
    - assets/xmlSat/arq_venda_008_Simples_Nacional.xml

  uses-material-design: true